[colors-dark]
alpha=1
foreground=c5c8c6
background=1d1f21
cursor=1d1f21 aeafad

regular0=1d1f21
regular1=912226
regular2=778900
regular3=ae7b00
regular4=1d2594
regular5=682a9b
regular6=2b6651
regular7=929593

bright0=969896
bright1=cc6666
bright2=b5bd68
bright3=f0c674
bright4=81a2be
bright5=b294bb
bright6=8abeb7
bright7=ecebec

[text-bindings]
\x1b[1;2F = Shift+KP_End
\x1b[1;2H = Shift+KP_Home

\x1b[27;6;65~ = Control+Shift+a
\x1b[27;6;66~ = Control+Shift+b
#\x1b[27;6;67~ = Control+Shift+c
\x1b[27;6;68~ = Control+Shift+d
\x1b[27;6;69~ = Control+Shift+e
\x1b[27;6;70~ = Control+Shift+f
\x1b[27;6;71~ = Control+Shift+g
\x1b[27;6;72~ = Control+Shift+h
\x1b[27;6;73~ = Control+Shift+i
\x1b[27;6;74~ = Control+Shift+j
\x1b[27;6;75~ = Control+Shift+k
\x1b[27;6;76~ = Control+Shift+l
\x1b[27;6;77~ = Control+Shift+m
#\x1b[27;6;78~ = Control+Shift+n
#\x1b[27;6;79~ = Control+Shift+o
#\x1b[27;6;80~ = Control+Shift+p
#\x1b[27;6;81~ = Control+Shift+q
#\x1b[27;6;82~ = Control+Shift+r
\x1b[27;6;83~ = Control+Shift+s
\x1b[27;6;84~ = Control+Shift+t
#\x1b[27;6;85~ = Control+Shift+u
#\x1b[27;6;86~ = Control+Shift+v
\x1b[27;6;87~ = Control+Shift+w
\x1b[27;6;88~ = Control+Shift+x
\x1b[27;6;89~ = Control+Shift+y
\x1b[27;6;90~ = Control+Shift+z
\x1b? = Alt+BackSpace

[key-bindings]
#clipboard-paste = none

prompt-prev=none
prompt-next=none

pipe-command-output=[wl-copy] Control+Shift+p

[scrollback]
indicator-position=none

[main]
#shell=zsh -c "fastfetch; zsh -i"
pad=10x10
font=Mononoki Nerd Font Mono:size=10
font-bold=Mononoki Nerd Font Mono:size=10:weight=bold
font-italic=Mononoki Nerd Font Mono:size=10:slant=italic
font-bold-italic=Mononoki Nerd Font Mono:size=10:weight=bold:slant=italic
